// This file is auto-generated by @hey-api/openapi-ts

export const ApiResponse_FormRegisterResponse_Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success',
            default: true
        },
        message: {
            type: 'string',
            title: 'Message',
            default: 'OK'
        },
        data: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        }
    },
    type: 'object',
    title: 'ApiResponse[FormRegisterResponse]'
} as const;

export const BatchResult_FormRegisterResponse_Schema = {
    properties: {
        succeeded: {
            items: {},
            type: 'array',
            title: 'Succeeded'
        },
        failed: {
            items: {},
            type: 'array',
            title: 'Failed'
        },
        total_count: {
            type: 'integer',
            title: 'Total Count'
        },
        success_count: {
            type: 'integer',
            title: 'Success Count'
        },
        fail_count: {
            type: 'integer',
            title: 'Fail Count'
        }
    },
    type: 'object',
    required: ['succeeded', 'failed', 'total_count', 'success_count', 'fail_count'],
    title: 'BatchResult[FormRegisterResponse]'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const FormApiResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success',
            default: true
        },
        message: {
            type: 'string',
            title: 'Message',
            default: 'OK'
        },
        data: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        }
    },
    type: 'object',
    title: 'FormApiResponse',
    description: 'Form 단일 응답 (제네릭 구체화)'
} as const;

export const FormListResponseSchema = {
    properties: {
        items: {
            items: {},
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page',
            default: 1
        },
        page_size: {
            type: 'integer',
            title: 'Page Size',
            default: 10
        },
        has_next: {
            type: 'boolean',
            title: 'Has Next',
            default: false
        },
        has_prev: {
            type: 'boolean',
            title: 'Has Prev',
            default: false
        }
    },
    type: 'object',
    required: ['items', 'total'],
    title: 'FormListResponse',
    description: 'Form 목록 응답 (제네릭 구체화)'
} as const;

export const FormRegisterRequestSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        content: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'FormRegisterRequest'
} as const;

export const FormRegisterResponseSchema = {
    properties: {
        idx: {
            type: 'integer',
            title: 'Idx'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At',
            description: '생성 시간'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At',
            description: '수정 시간'
        },
        created_by: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By',
            description: '생성자 사용자 ID'
        },
        updated_by: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated By',
            description: '수정자 사용자 ID'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        content: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'FormRegisterResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const KeyValuePair_str__FormRegisterResponse_Schema = {
    properties: {
        key: {
            title: 'Key'
        },
        value: {
            title: 'Value'
        }
    },
    type: 'object',
    required: ['key', 'value'],
    title: 'KeyValuePair[str, FormRegisterResponse]'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PaginatedResponse_FormRegisterResponse_Schema = {
    properties: {
        items: {
            items: {},
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        page: {
            type: 'integer',
            title: 'Page',
            default: 1
        },
        page_size: {
            type: 'integer',
            title: 'Page Size',
            default: 10
        },
        has_next: {
            type: 'boolean',
            title: 'Has Next',
            default: false
        },
        has_prev: {
            type: 'boolean',
            title: 'Has Prev',
            default: false
        }
    },
    type: 'object',
    required: ['items', 'total'],
    title: 'PaginatedResponse[FormRegisterResponse]'
} as const;

export const SendMailRequestSchema = {
    properties: {
        subject: {
            type: 'string',
            title: 'Subject'
        },
        body: {
            type: 'string',
            title: 'Body'
        },
        receivers: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Receivers'
        },
        sender_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sender Name'
        }
    },
    type: 'object',
    required: ['subject', 'body', 'receivers'],
    title: 'SendMailRequest',
    description: '메일 발송 요청 스키마'
} as const;

export const SendMailResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        status: {
            type: 'integer',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        }
    },
    type: 'object',
    required: ['success', 'status', 'message'],
    title: 'SendMailResponse',
    description: '메일 발송 응답 스키마'
} as const;

export const SendSMSRequestSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        receivers: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Receivers'
        }
    },
    type: 'object',
    required: ['title', 'message', 'receivers'],
    title: 'SendSMSRequest',
    description: 'SMS 발송 요청 스키마'
} as const;

export const SendSMSResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        status: {
            type: 'integer',
            title: 'Status'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        }
    },
    type: 'object',
    required: ['success', 'status', 'message'],
    title: 'SendSMSResponse',
    description: 'SMS 발송 응답 스키마'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: '비밀번호 변경 요청'
} as const;

export const UserSchema = {
    properties: {
        idx: {
            type: 'integer',
            title: 'Idx'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At',
            description: '생성 시간'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At',
            description: '수정 시간'
        },
        created_by: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By',
            description: '생성자 사용자 ID'
        },
        updated_by: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated By',
            description: '수정자 사용자 ID'
        },
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        hashed_password: {
            type: 'string',
            title: 'Hashed Password'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        register_date: {
            type: 'string',
            format: 'date-time',
            title: 'Register Date'
        },
        useYN: {
            type: 'boolean',
            title: 'Useyn',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        }
    },
    type: 'object',
    required: ['user_id', 'hashed_password', 'email', 'name'],
    title: 'User'
} as const;

export const UserOutSchema = {
    properties: {
        idx: {
            type: 'integer',
            title: 'Idx'
        },
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        register_date: {
            type: 'string',
            format: 'date-time',
            title: 'Register Date'
        },
        useYN: {
            type: 'boolean',
            title: 'Useyn'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        }
    },
    type: 'object',
    required: ['idx', 'user_id', 'email', 'name', 'register_date', 'useYN', 'is_superuser'],
    title: 'UserOut',
    description: '유저 공개 정보 응답'
} as const;

export const UserRegisterSchema = {
    properties: {
        user_id: {
            type: 'string',
            maxLength: 50,
            minLength: 4,
            title: 'User Id'
        },
        plain_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Plain Password'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['user_id', 'plain_password', 'email', 'name'],
    title: 'UserRegister',
    description: '회원가입 요청'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        useYN: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Useyn'
        },
        plain_password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plain Password'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: '유저 정보 수정 요청 (관리자용)'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: '본인 정보 수정 요청'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/User'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: '유저 목록 응답'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const app__models__MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const app__models__UserModels__MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: '일반 메시지 응답'
} as const;