// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { DirectsendMailSendMailData, DirectsendMailSendMailResponse, DirectsendMailGetMailServiceStatusResponse, DirectsendSmsSendSmsData, DirectsendSmsSendSmsResponse, DirectsendSmsGetSmsServiceStatusResponse, FormRegisterRegisterFormData, FormRegisterRegisterFormResponse, FormRegisterGetFormWithWrapperData, FormRegisterGetFormWithWrapperResponse, FormRegisterGetFormListData, FormRegisterGetFormListResponse, FormRegisterGetFormDetailData, FormRegisterGetFormDetailResponse, FormRegisterGetAllFormsResponse, FormRegisterBatchCreateFormsData, FormRegisterBatchCreateFormsResponse, FormRegisterGetFormConfigData, FormRegisterGetFormConfigResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserByIdxData, UsersReadUserByIdxResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class DirectsendMailService {
    /**
     * Send Mail
     * 메일 발송
     *
     * - 로그인한 사용자만 사용 가능
     * - DirectSend API를 통해 메일 발송
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SendMailResponse Successful Response
     * @throws ApiError
     */
    public static sendMail(data: DirectsendMailSendMailData): CancelablePromise<DirectsendMailSendMailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/directsend/mail/send',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Mail Service Status
     * 메일 서비스 상태 확인
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getMailServiceStatus(): CancelablePromise<DirectsendMailGetMailServiceStatusResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/directsend/mail/status'
        });
    }
}

export class DirectsendSmsService {
    /**
     * Send Sms
     * SMS 발송
     *
     * - 로그인한 사용자만 사용 가능
     * - DirectSend API를 통해 SMS 발송
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SendSMSResponse Successful Response
     * @throws ApiError
     */
    public static sendSms(data: DirectsendSmsSendSmsData): CancelablePromise<DirectsendSmsSendSmsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/directsend/sms/send',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Sms Service Status
     * SMS 서비스 상태 확인
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getSmsServiceStatus(): CancelablePromise<DirectsendSmsGetSmsServiceStatusResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/directsend/sms/status'
        });
    }
}

export class FormRegisterService {
    /**
     * Register Form
     * @param data The data for the request.
     * @param data.requestBody
     * @returns FormRegisterResponse Successful Response
     * @throws ApiError
     */
    public static registerForm(data: FormRegisterRegisterFormData): CancelablePromise<FormRegisterRegisterFormResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/formRegister/register',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Form With Wrapper
     * 제네릭 래퍼로 감싼 단일 응답
     * @param data The data for the request.
     * @param data.formId
     * @returns ApiResponse_FormRegisterResponse_ Successful Response
     * @throws ApiError
     */
    public static getFormWithWrapper(data: FormRegisterGetFormWithWrapperData): CancelablePromise<FormRegisterGetFormWithWrapperResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/formRegister/single/{form_id}',
            path: {
                form_id: data.formId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Form List
     * 제네릭 페이지네이션 응답
     * @param data The data for the request.
     * @param data.page
     * @param data.pageSize
     * @returns PaginatedResponse_FormRegisterResponse_ Successful Response
     * @throws ApiError
     */
    public static getFormList(data: FormRegisterGetFormListData = {}): CancelablePromise<FormRegisterGetFormListResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/formRegister/list',
            query: {
                page: data.page,
                page_size: data.pageSize
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Form Detail
     * 구체화된 제네릭 응답 클래스
     * @param data The data for the request.
     * @param data.formId
     * @returns FormApiResponse Successful Response
     * @throws ApiError
     */
    public static getFormDetail(data: FormRegisterGetFormDetailData): CancelablePromise<FormRegisterGetFormDetailResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/formRegister/detail/{form_id}',
            path: {
                form_id: data.formId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get All Forms
     * 구체화된 페이지네이션 응답 클래스
     * @returns FormListResponse Successful Response
     * @throws ApiError
     */
    public static getAllForms(): CancelablePromise<FormRegisterGetAllFormsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/formRegister/all'
        });
    }
    
    /**
     * Batch Create Forms
     * 배치 처리 결과 제네릭
     * @param data The data for the request.
     * @param data.requestBody
     * @returns BatchResult_FormRegisterResponse_ Successful Response
     * @throws ApiError
     */
    public static batchCreateForms(data: FormRegisterBatchCreateFormsData): CancelablePromise<FormRegisterBatchCreateFormsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/formRegister/batch',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Form Config
     * 다중 타입 파라미터 제네릭
     * @param data The data for the request.
     * @param data.key
     * @returns KeyValuePair_str__FormRegisterResponse_ Successful Response
     * @throws ApiError
     */
    public static getFormConfig(data: FormRegisterGetFormConfigData): CancelablePromise<FormRegisterGetFormConfigResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/formRegister/config/{key}',
            path: {
                key: data.key
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserOut Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns app__models__Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns app__models__Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * 유저 목록 조회 (관리자 전용)
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * 새 유저 생성 (관리자 전용)
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserOut Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Idx
     * 특정 유저 조회 (관리자 전용)
     * @param data The data for the request.
     * @param data.userIdx
     * @returns UserOut Successful Response
     * @throws ApiError
     */
    public static readUserByIdx(data: UsersReadUserByIdxData): CancelablePromise<UsersReadUserByIdxResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_idx}',
            path: {
                user_idx: data.userIdx
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * 유저 정보 수정 (관리자 전용)
     * @param data The data for the request.
     * @param data.userIdx
     * @param data.requestBody
     * @returns UserOut Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_idx}',
            path: {
                user_idx: data.userIdx
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * 유저 삭제 (관리자 전용)
     * @param data The data for the request.
     * @param data.userIdx
     * @returns app__models__UserModels__Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_idx}',
            path: {
                user_idx: data.userIdx
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * 회원가입 (로그인 불필요)
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserOut Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * 현재 로그인한 유저 정보 조회
     * @returns UserOut Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * 본인 계정 삭제
     * @returns app__models__UserModels__Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * 본인 정보 수정
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserOut Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * 본인 비밀번호 변경
     * @param data The data for the request.
     * @param data.requestBody
     * @returns app__models__UserModels__Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns app__models__Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}