// This file is auto-generated by @hey-api/openapi-ts

/**
 * 제네릭 API 응답 래퍼
 */
export type ApiResponse = {
    success?: boolean;
    message?: string;
    data?: (unknown | null);
};

export type ApiResponse_PublicFormResponse_ = {
    success?: boolean;
    message?: string;
    data?: (unknown | null);
};

export type app__models__Message = {
    message: string;
};

/**
 * 일반 메시지 응답
 */
export type app__models__UserModels__Message = {
    message: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Form 단일 응답 (제네릭 구체화)
 */
export type FormApiResponse = {
    success?: boolean;
    message?: string;
    data?: (unknown | null);
};

/**
 * 폼 생성 요청
 */
export type FormCreateRequest = {
    uuid?: (string | null);
    category?: string;
    title: string;
    description?: (string | null);
    JSONSchema?: {
        [key: string]: unknown;
    };
    UISchema?: {
        [key: string]: unknown;
    };
    Theme?: string;
};

/**
 * Form 목록 응답 (제네릭 구체화)
 */
export type FormListResponse = {
    items: Array<unknown>;
    total: number;
    page?: number;
    page_size?: number;
    has_next?: boolean;
    has_prev?: boolean;
};

/**
 * FormPublish 단일 응답
 */
export type FormPublishApiResponse = {
    success?: boolean;
    message?: string;
    data?: (unknown | null);
};

/**
 * 폼 배포 일괄 생성 요청
 */
export type FormPublishBatchRequest = {
    receivers: Array<{
        [key: string]: unknown;
    }>;
    expired_days?: number;
};

/**
 * 폼 배포 생성 요청
 */
export type FormPublishCreateRequest = {
    receiver: string;
    receiver_name?: (string | null);
    expired_days?: number;
};

/**
 * FormPublish 목록 응답
 */
export type FormPublishListResponse = {
    items: Array<unknown>;
    total: number;
    page?: number;
    page_size?: number;
    has_next?: boolean;
    has_prev?: boolean;
};

/**
 * 폼 배포 수정 요청
 */
export type FormPublishUpdateRequest = {
    receiver?: (string | null);
    receiver_name?: (string | null);
    expired_at?: (string | null);
    is_submitted?: (boolean | null);
};

/**
 * 폼 수정 요청
 */
export type FormUpdateRequest = {
    category?: (string | null);
    title?: (string | null);
    description?: (string | null);
    JSONSchema?: ({
    [key: string]: unknown;
} | null);
    UISchema?: ({
    [key: string]: unknown;
} | null);
    Theme?: (string | null);
    useYN?: (boolean | null);
    publish_status?: (PublishStatus | null);
    publish_start_at?: (string | null);
    publish_end_at?: (string | null);
    max_responses?: (number | null);
    allow_anonymous?: (boolean | null);
    require_login?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * 공개 폼 제출 요청
 */
export type PublicFormSubmitRequest = {
    responseData: {
        [key: string]: unknown;
    };
};

/**
 * 배포 상태
 */
export type PublishStatus = 'draft' | 'scheduled' | 'published' | 'closed';

/**
 * 메일 발송 요청 스키마
 */
export type SendMailRequest = {
    subject: string;
    body: string;
    receivers: Array<{
        [key: string]: unknown;
    }>;
    sender_name?: (string | null);
};

/**
 * 메일 발송 응답 스키마
 */
export type SendMailResponse = {
    success: boolean;
    status: number;
    message: string;
    data?: ({
    [key: string]: unknown;
} | null);
};

/**
 * SMS 발송 요청 스키마
 */
export type SendSMSRequest = {
    title: string;
    message: string;
    receivers: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * SMS 발송 응답 스키마
 */
export type SendSMSResponse = {
    success: boolean;
    status: number;
    message: string;
    data?: ({
    [key: string]: unknown;
} | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * 비밀번호 변경 요청
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type User = {
    idx?: number;
    /**
     * 생성 시간
     */
    created_at?: (string | null);
    /**
     * 수정 시간
     */
    updated_at?: (string | null);
    /**
     * 생성자 사용자 ID
     */
    created_by?: (number | null);
    /**
     * 수정자 사용자 ID
     */
    updated_by?: (number | null);
    user_id: string;
    hashed_password: string;
    email: string;
    name: string;
    register_date?: string;
    useYN?: boolean;
    is_superuser?: boolean;
};

/**
 * 유저 공개 정보 응답
 */
export type UserOut = {
    idx: number;
    user_id: string;
    email: string;
    name: string;
    register_date: string;
    useYN: boolean;
    is_superuser: boolean;
};

/**
 * 회원가입 요청
 */
export type UserRegister = {
    user_id: string;
    plain_password: string;
    email: string;
    name: string;
};

/**
 * 유저 목록 응답
 */
export type UsersPublic = {
    data: Array<User>;
    count: number;
};

/**
 * 유저 정보 수정 요청 (관리자용)
 */
export type UserUpdate = {
    email?: (string | null);
    name?: (string | null);
    useYN?: (boolean | null);
    plain_password?: (string | null);
};

/**
 * 본인 정보 수정 요청
 */
export type UserUpdateMe = {
    email?: (string | null);
    name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DirectsendMailSendMailData = {
    requestBody: SendMailRequest;
};

export type DirectsendMailSendMailResponse = (SendMailResponse);

export type DirectsendMailGetMailServiceStatusResponse = ({
    [key: string]: unknown;
});

export type DirectsendSmsSendSmsData = {
    requestBody: SendSMSRequest;
};

export type DirectsendSmsSendSmsResponse = (SendSMSResponse);

export type DirectsendSmsGetSmsServiceStatusResponse = ({
    [key: string]: unknown;
});

export type FormRegisterGetFormListData = {
    page?: number;
    pageSize?: number;
};

export type FormRegisterGetFormListResponse = (FormListResponse);

export type FormRegisterCreateFormData = {
    requestBody: FormCreateRequest;
};

export type FormRegisterCreateFormResponse = (FormApiResponse);

export type FormRegisterGetFormData = {
    formUuid: string;
};

export type FormRegisterGetFormResponse = (FormApiResponse);

export type FormRegisterUpdateFormData = {
    formUuid: string;
    requestBody: FormUpdateRequest;
};

export type FormRegisterUpdateFormResponse = (FormApiResponse);

export type FormRegisterDeleteFormData = {
    formUuid: string;
};

export type FormRegisterDeleteFormResponse = (unknown);

export type FormRegisterGetFormPublishesData = {
    formUuid: string;
    page?: number;
    pageSize?: number;
};

export type FormRegisterGetFormPublishesResponse = (FormPublishListResponse);

export type FormRegisterCreateFormPublishData = {
    formUuid: string;
    requestBody: FormPublishCreateRequest;
};

export type FormRegisterCreateFormPublishResponse = (FormPublishApiResponse);

export type FormRegisterCreateFormPublishBatchData = {
    formUuid: string;
    requestBody: FormPublishBatchRequest;
};

export type FormRegisterCreateFormPublishBatchResponse = (ApiResponse);

export type FormRegisterUpdateFormPublishData = {
    formUuid: string;
    publishIdx: number;
    requestBody: FormPublishUpdateRequest;
};

export type FormRegisterUpdateFormPublishResponse = (FormPublishApiResponse);

export type FormRegisterDeleteFormPublishData = {
    formUuid: string;
    publishIdx: number;
};

export type FormRegisterDeleteFormPublishResponse = (unknown);

export type FormRegisterGetPublicFormData = {
    token: string;
};

export type FormRegisterGetPublicFormResponse = (ApiResponse_PublicFormResponse_);

export type FormRegisterSubmitPublicFormData = {
    requestBody: PublicFormSubmitRequest;
    token: string;
};

export type FormRegisterSubmitPublicFormResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserOut);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (app__models__Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (app__models__Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserOut);

export type UsersReadUserMeResponse = (UserOut);

export type UsersDeleteUserMeResponse = (app__models__UserModels__Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserOut);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (app__models__UserModels__Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserRegister;
};

export type UsersCreateUserResponse = (UserOut);

export type UsersReadUserByIdxData = {
    userIdx: number;
};

export type UsersReadUserByIdxResponse = (UserOut);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userIdx: number;
};

export type UsersUpdateUserResponse = (UserOut);

export type UsersDeleteUserData = {
    userIdx: number;
};

export type UsersDeleteUserResponse = (app__models__UserModels__Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (app__models__Message);

export type UtilsHealthCheckResponse = (boolean);