"""empty message

Revision ID: 03eb13fa2197
Revises: 1a31ce608336
Create Date: 2025-11-27 12:16:59.651171

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '03eb13fa2197'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('item_owner_id_fkey'), 'item', type_='foreignkey')
    op.add_column('user', sa.Column('idx', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('register_date', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('useYN', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_user_user_idx'), 'user', ['user_idx'], unique=True)
    op.drop_column('user', 'id')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_column('user', 'useYN')
    op.drop_column('user', 'register_date')
    op.drop_column('user', 'name')
    op.drop_column('user', 'user_id')
    op.drop_column('user', 'updated_by')
    op.drop_column('user', 'created_by')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'idx')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(op.f('item_owner_id_fkey'), 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
