"""add_publish_fields_to_form

Revision idx: 26a64d83f39e
Revises: a709f6aea024
Create Date: 2025-11-29 22:27:56.301018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26a64d83f39e'
down_revision: Union[str, None] = 'a709f6aea024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'CLOSED', name='publishstatus').create(op.get_bind())
    op.add_column('formpublishtable', sa.Column('receiver_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('formpublishtable', sa.Column('is_submitted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('formpublishtable', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_formpublishtable_token'), 'formpublishtable', ['token'], unique=True)
    op.add_column('formtable', sa.Column('publish_status', postgresql.ENUM('DRAFT', 'SCHEDULED', 'PUBLISHED', 'CLOSED', name='publishstatus', create_type=False), nullable=False, server_default='DRAFT'))
    op.add_column('formtable', sa.Column('publish_start_at', sa.DateTime(), nullable=True))
    op.add_column('formtable', sa.Column('publish_end_at', sa.DateTime(), nullable=True))
    op.add_column('formtable', sa.Column('max_responses', sa.Integer(), nullable=True))
    op.add_column('formtable', sa.Column('allow_anonymous', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('formtable', sa.Column('require_login', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formtable', 'require_login')
    op.drop_column('formtable', 'allow_anonymous')
    op.drop_column('formtable', 'max_responses')
    op.drop_column('formtable', 'publish_end_at')
    op.drop_column('formtable', 'publish_start_at')
    op.drop_column('formtable', 'publish_status')
    op.drop_index(op.f('ix_formpublishtable_token'), table_name='formpublishtable')
    op.drop_column('formpublishtable', 'submitted_at')
    op.drop_column('formpublishtable', 'is_submitted')
    op.drop_column('formpublishtable', 'receiver_name')
    sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'CLOSED', name='publishstatus').drop(op.get_bind())
    # ### end Alembic commands ###
