"""empty message

Revision idx: 794272511202
Revises: 2ea957562a5e
Create Date: 2025-11-27 15:55:38.380760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '794272511202'
down_revision: Union[str, None] = '2ea957562a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formpublishtable',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('form_idx', sa.Integer(), nullable=False),
    sa.Column('receiver', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('responseSchema', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['form_idx'], ['formtable.idx'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    op.add_column('formtable', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('formtable', sa.Column('JSONSchema', sa.JSON(), nullable=True))
    op.add_column('formtable', sa.Column('UISchema', sa.JSON(), nullable=True))
    op.add_column('formtable', sa.Column('Theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('formtable', sa.Column('useYN', sa.Boolean(), nullable=False))
    op.drop_column('formtable', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formtable', sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('formtable', 'useYN')
    op.drop_column('formtable', 'Theme')
    op.drop_column('formtable', 'UISchema')
    op.drop_column('formtable', 'JSONSchema')
    op.drop_column('formtable', 'category')
    op.drop_table('formpublishtable')
    # ### end Alembic commands ###
