"""empty message

Revision ID: 9ea93604f7bb
Revises: 59a31537fe16
Create Date: 2025-11-27 12:21:34.496281

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9ea93604f7bb'
down_revision = '59a31537fe16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
