"""empty message

Revision ID: d1b0753491f8
Revises: 3ca7ba3d0521
Create Date: 2025-11-27 14:01:47.077736

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd1b0753491f8'
down_revision = '3ca7ba3d0521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
