"""empty message

Revision idx: f57ea1a2d77f
Revises: 794272511202
Create Date: 2025-11-28 16:47:21.463356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'f57ea1a2d77f'
down_revision: Union[str, None] = '794272511202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formtable', sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False))
    op.create_index(op.f('ix_formtable_uuid'), 'formtable', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formtable_uuid'), table_name='formtable')
    op.drop_column('formtable', 'uuid')
    # ### end Alembic commands ###
