/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutDirectsendSmsRouteImport } from './routes/_layout/directsend-sms'
import { Route as LayoutDirectsendMailRouteImport } from './routes/_layout/directsend-mail'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutFormRegisterTestRouteImport } from './routes/_layout/form-register/test'
import { Route as LayoutFormRegisterListRouteImport } from './routes/_layout/form-register/list'
import { Route as LayoutFormRegisterIdxRouteImport } from './routes/_layout/form-register/$idx'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDirectsendSmsRoute = LayoutDirectsendSmsRouteImport.update({
  id: '/directsend-sms',
  path: '/directsend-sms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDirectsendMailRoute = LayoutDirectsendMailRouteImport.update({
  id: '/directsend-mail',
  path: '/directsend-mail',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormRegisterTestRoute = LayoutFormRegisterTestRouteImport.update({
  id: '/form-register/test',
  path: '/form-register/test',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormRegisterListRoute = LayoutFormRegisterListRouteImport.update({
  id: '/form-register/list',
  path: '/form-register/list',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormRegisterIdxRoute = LayoutFormRegisterIdxRouteImport.update({
  id: '/form-register/$idx',
  path: '/form-register/$idx',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/directsend-mail': typeof LayoutDirectsendMailRoute
  '/directsend-sms': typeof LayoutDirectsendSmsRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/form-register/$idx': typeof LayoutFormRegisterIdxRoute
  '/form-register/list': typeof LayoutFormRegisterListRoute
  '/form-register/test': typeof LayoutFormRegisterTestRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/directsend-mail': typeof LayoutDirectsendMailRoute
  '/directsend-sms': typeof LayoutDirectsendSmsRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/form-register/$idx': typeof LayoutFormRegisterIdxRoute
  '/form-register/list': typeof LayoutFormRegisterListRoute
  '/form-register/test': typeof LayoutFormRegisterTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/directsend-mail': typeof LayoutDirectsendMailRoute
  '/_layout/directsend-sms': typeof LayoutDirectsendSmsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/form-register/$idx': typeof LayoutFormRegisterIdxRoute
  '/_layout/form-register/list': typeof LayoutFormRegisterListRoute
  '/_layout/form-register/test': typeof LayoutFormRegisterTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/directsend-mail'
    | '/directsend-sms'
    | '/items'
    | '/settings'
    | '/'
    | '/form-register/$idx'
    | '/form-register/list'
    | '/form-register/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/directsend-mail'
    | '/directsend-sms'
    | '/items'
    | '/settings'
    | '/'
    | '/form-register/$idx'
    | '/form-register/list'
    | '/form-register/test'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/directsend-mail'
    | '/_layout/directsend-sms'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/form-register/$idx'
    | '/_layout/form-register/list'
    | '/_layout/form-register/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/directsend-sms': {
      id: '/_layout/directsend-sms'
      path: '/directsend-sms'
      fullPath: '/directsend-sms'
      preLoaderRoute: typeof LayoutDirectsendSmsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/directsend-mail': {
      id: '/_layout/directsend-mail'
      path: '/directsend-mail'
      fullPath: '/directsend-mail'
      preLoaderRoute: typeof LayoutDirectsendMailRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-register/test': {
      id: '/_layout/form-register/test'
      path: '/form-register/test'
      fullPath: '/form-register/test'
      preLoaderRoute: typeof LayoutFormRegisterTestRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-register/list': {
      id: '/_layout/form-register/list'
      path: '/form-register/list'
      fullPath: '/form-register/list'
      preLoaderRoute: typeof LayoutFormRegisterListRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form-register/$idx': {
      id: '/_layout/form-register/$idx'
      path: '/form-register/$idx'
      fullPath: '/form-register/$idx'
      preLoaderRoute: typeof LayoutFormRegisterIdxRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDirectsendMailRoute: typeof LayoutDirectsendMailRoute
  LayoutDirectsendSmsRoute: typeof LayoutDirectsendSmsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFormRegisterIdxRoute: typeof LayoutFormRegisterIdxRoute
  LayoutFormRegisterListRoute: typeof LayoutFormRegisterListRoute
  LayoutFormRegisterTestRoute: typeof LayoutFormRegisterTestRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDirectsendMailRoute: LayoutDirectsendMailRoute,
  LayoutDirectsendSmsRoute: LayoutDirectsendSmsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFormRegisterIdxRoute: LayoutFormRegisterIdxRoute,
  LayoutFormRegisterListRoute: LayoutFormRegisterListRoute,
  LayoutFormRegisterTestRoute: LayoutFormRegisterTestRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
